import re
from typing import Callable


def generator_numbers(text: str):
    """
    Generate floating-point numbers found in a text string.
    This generator function searches through the provided text for all
    floating-point numbers (numbers with a decimal point) and yields each
    one as a float value.
    Args:
        text (str): The input string to search for floating-point numbers.
    Yields:
        float: Each floating-point number found in the text.
    """

    # Regex pattern to find all floating-point numbers in the text
    pattern = r'\d+\.\d+'

    numbers = re.findall(pattern, text)
    
    # Create a generator that yields each number as a float
    for num in numbers:
        yield float(num)

def sum_profit(text: str, func: Callable):
    """
    Calculate the total sum of numbers generated by a callable function.
    Args:
        text (str): The input text to be processed by the function.
        func (Callable): A callable function that generates numbers when given the text.
    Returns:
        float: The sum of all numbers generated by the function.
    """

    total = 0.0

    #sum up all the numbers generated by the generator function
    for number in func(text):
        total += number
    
    return total


text = "Загальний дохід працівника складається з декількох частин: 1000.01 як основний дохід, доповнений додатковими надходженнями 27.45 і 324.00 доларів."
total_income = sum_profit(text, generator_numbers)
print(f"Загальний дохід: {total_income}")

# Загальний дохід: 1351.46